### ISSUE TITLE
Executing the usage example leads to: Cannot read property 'theme' of undefined

### ISSUE THREAD

**Issue by HorstMumpitz** [allthings/elements#1]
Hi there, 

First of all thank you a lot for making Elements publicly available. I'm really looking forward to working with it. 

I've found a small issue. Executing the described usage example leads to an error: "Cannot read property 'theme' of undefined". The [Examples Project](https://github.com/allthings/elements-example/blob/master/src/TodoApp.js) wraps everything within a `<ThemeProvider>` which fixes the issue. Therefore it seems that the usage of a ThemeProvider is necessary. 

Two solutions could be possible: 
1. Adapting the Usage example
2. Make the usage of a ThemeProvider optional

Cheers, 
Dennis

**Comment by yamafaktory** [comment]
Hi @HorstMumpitz,

Thanks a lot for your great feedback! We're going to fix that by updating the documentation.

**Comment by mosch** [comment]
Done, Themes are now completely optional.
