### ISSUE TITLE
redirect to not-found if no matching route is defined

### ISSUE THREAD

**Issue by adashst** [allthings/elements#117]
If a route doesn't match, currently the parent route is displayed.
This my cause some confusion as there is no feedback, that the current route is invalid.

I think it would be cool to redirect the user to a well styled `not-found` page if the current route is not found.

**Comment by mosch** [comment]
I guess this refers to the example [HorizontalRouter](https://github.com/allthings/elements-example/blob/master/horizontal-view/src/HorizontalRouter.js) from the [examples](https://github.com/allthings/elements-example/) so le'ts move it to there.

**Comment by adashst** [comment]
@mosch of course thanks!
