### ISSUE TITLE
Fetch not available in SSR, find a more generic solution 💡

### ISSUE THREAD

**Issue by yamafaktory** [allthings/elements#137]
We have addressed the issue in the CDNIntlProvider component https://github.com/allthings/elements/blob/master/src/behaviour/CDNIntlProvider.jsx#L25 component but sadly this needs to be also fixed in the Icon one https://github.com/allthings/elements/blob/master/src/atoms/Icon.jsx#L244.

Let's find a better generic solution 🚀!

**Comment by yamafaktory** [comment]
cc/ @mosch

**Comment by mosch** [comment]
I think it's ok for this library to expect `global.fetch` to be there. So the user land needs to make sure it's polyfilled. Would be something to add to the docs anyway. Any opinions on this? 
ping @dan-lee

**Comment by dan-lee** [comment]
I think we should pull in `isomorphic-fetch` rather than expect `fetch` to be there. It might not seem obvious why and when it should be added. And it should work without reading the docs first imo.

**Comment by mosch** [comment]
I like it: https://github.com/allthings/elements/pull/139

**Comment by yamafaktory** [comment]
Let's merge it 🚀.

**Comment by yamafaktory** [comment]
And let's close that!

**Comment by adieuadieu** [comment]
@dan-lee I recommend approaching new uses (new contexts) of `isomorphic-fetch` with caution.. The module is dated/unmaintained.

**Comment by adieuadieu** [comment]
Consider [cross-fetch](https://github.com/lquixada/cross-fetch) as an alternative.

**Comment by dan-lee** [comment]
I had quick glance at the code and it looks very much the same to me.  But yes, there's almost no maintenance for `isomorphic-fetch` so I wouldn't mind switching to `cross-fetch`.

**Comment by yamafaktory** [comment]
One small thing I've noticed is that `fbjs` already uses `isomorphic-fetch` as an internal dependency (https://github.com/facebook/fbjs/blob/master/packages/fbjs/package.json#L63).

**Comment by mosch** [comment]
Seems reasonable to switch to cross-fetch, but we should also do so in _other projects_ where we are using elements.

**Comment by yamafaktory** [comment]
Not quite sure about fbjs and isomorphic-fetch not being exposed. Will have to check as I've initially seen it in my yarn.lock file while switching to cross-fetch.

**Comment by mosch** [comment]
Should we close this since we added cross-fetch?
