### ISSUE TITLE
HorizontalView breaks in Edge

### ISSUE THREAD

**Issue by HorstMumpitz** [allthings/elements#157]
The `HorizontalView` works as expected on all major browsers except IE Edge (tested von version 16).  I can observe a weird scrolling behaviour. Probably it has something to do how heights and CSS units are utilised.

**Comment by dan-lee** [comment]
Thanks for reporting this. I actually saw the same behaviour on Chrome. A simple wrapper View with `overflow: hidden` was enough to get rid of this.

**Comment by dan-lee** [comment]
@HorstMumpitz ping :)

**Comment by HorstMumpitz** [comment]
@dan-lee The fix did not solve my particular Edge bug but seems to work in general. In my case most of my view use additionally a `SimpleLayout`.

**Comment by dan-lee** [comment]
Could you perhaps provide a simple [CodeSandbox](https://codesandbox.io/)?
I tried it with the [horizontal view example](https://github.com/allthings/elements-example/tree/master/horizontal-view) in Edge and it worked out. But maybe your circumstances change things

**Comment by fivenp** [comment]
Is this still valid? It looks fine in our implementations afaik - maybe we need a better documentation for it (suggest we close it due to inactivity for now?)
