### ISSUE TITLE
Double rendering because of CDNIntlProvider mismatch

### ISSUE THREAD

**Issue by dan-lee** [allthings/elements#176]
When not passing the messages on client side but having them on server side a mismatch happens, and the whole app renders twice.
> Warning: Expected server HTML to contain a matching \<div\> in \<div\>

In my opinion this should not happen. 

Text mismatches still happen but these do not cause a re-render of the whole app, e.g.:
> Warning: Text content did not match. Server: "Hang on..." Client: "Hold on..."

We simply could remove `this.state.loaded` to change this behaviour:
https://github.com/allthings/elements/blob/2b86f249708ded2af4e84afba0f978360e359cf9/src/behaviour/CDNIntlProvider.jsx#L91-L97

**Comment by mosch** [comment]
Hey @dan-lee, good catch! I think we should not render everything if it's not loaded yet. 
We can pass in messages to the component and it should be in the loaded state right away. So we I see two options there:
 1. Load messages using `loadLanguage` before you hydrate on client side and pass them directly to the IntlProvider
 2. Render messages into the DOM when you do SSR, so the IntlProvider can pick them up from there without any delay

Let's find the best option and add this to the docs!

**Comment by dan-lee** [comment]
In my opinion we should render *something* to prevent the mismatch and eventually prevent a complete remount of the app. I'd prefer flashing text messages of everything disappearing and appearing again.

Of course this *shouldn't* happen when the messages are rehydrated from the server. But in some cases this may not happen (for some reason) and we would prevent a remount, virtually flashing the whole page.

I like your idea mentioned in the last paragraph, but I am not sure if this can work out. We can give it a try 👍

**Comment by dan-lee** [comment]
Fixed with #178
