### ISSUE TITLE
Icon component has strange default size

### ISSUE THREAD

**Issue by dan-lee** [allthings/elements#198]
The default icon size uses a strange and uneven default value:

https://github.com/allthings/elements/blob/54b982f2d66d1ae6fda45daa38e577192214cb8c/src/atoms/Icon.jsx#L179-L182

None of our allowed values (besides the numeric values) match it:

https://github.com/allthings/elements/blob/54b982f2d66d1ae6fda45daa38e577192214cb8c/src/atoms/Icon.jsx#L210-L223

We should maybe set the default to `m` .

**Comment by fivenp** [comment]
I've been digging through some code to find the places where we actually DON'T supply a `size` prop to the `<Icon />`... 

So far I've found only one single place and in that case it would be no problem at all to change the default to `m` - so lets go for it <3
