### ISSUE TITLE
Implement standard input elments

### ISSUE THREAD

**Issue by HorstMumpitz** [allthings/elements#3]
The current collection of Elements does not provide any inputs. Therefore I suggest to implement a very minimal set of controls: 

- Text Input 
- Select

**Comment by mosch** [comment]
TextInput is done, we still need to get Select in

**Comment by mosch** [comment]
Update: We are currently doing some work on the Select / Option thing. I'll keep you updated!

**Comment by fivenp** [comment]
Fixed by #593
