### ISSUE TITLE
Make sizes and font properties globally available

### ISSUE THREAD

**Issue by HorstMumpitz** [allthings/elements#7]
Setting font sizes and properties on custom elements needs manual style adaptions and copying of values. It would be an interesting take to make general styles available. This could be something easy like exporting styles of a text element or providing them through a theme.

**Comment by mosch** [comment]
Hey @HorstMumpitz, can you give me an example of the manual style adaptations and copying you need to make to it gets more clear what you mean?

**Comment by HorstMumpitz** [comment]
Sure. Let's assume that I want to provide custom text input elements. In the current situation font-sizes and properties have to be configured with custom CSS like. 

```javascript
import React from 'react';
import View from '@allthings/elements/atoms/View';
import { css } from 'glamor';

const styles = {
  input: css({
    'fontSize': 18,
    'borderWidth': 0,
    'margin': 5,
    'width': '100%',
    'outline': 'none'
};


export class TextInput extends React.Component {
  render() {  
    return (
      <View>
        <textarea {...styles.input} />
      </View>
    )
  }
}
```

But some properties could be part of elements or the Theme. Please take a look on the changed font size. 

```javascript
import React from 'react';
import View from '@allthings/elements/atoms/View';
import { availableSizes } from '@allthings/elements/atoms/Text';
import { css } from 'glamor';

const styles = {
  input: css({
    'fontSize':  availableSizes.xl,
    'borderWidth': 0,
    'margin': 5,
    'width': '100%',
    'outline': 'none'
};
```

Such a mechanism provides two advantages: 
1. Constants provided by Elements are the ground truth and avoid magic numbers in code 
2. When parts of the styling within Elements change code maintenance gets reduced.

**Comment by mosch** [comment]
@HorstMumpitz we are now exporting a function to create text styles. https://github.com/allthings/elements/pull/154/files#diff-54fdd351ae2ad12ed1c3da9c1025262d

I think this will also fix this?

**Comment by HorstMumpitz** [comment]
👍 Thank you for fixing. Looks good to me.
